#services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0
#    environment:
#      KC_HOSTNAME: localhost
#      KC_HOSTNAME_PORT: 7080
#      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HEALTH_ENABLED: "true"
#      KC_LOG_LEVEL: info
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
#      interval: 15s
#      timeout: 2s
#      retries: 15
#    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm"]
#    volumes: # Ignore if you don't have realm-export.json to migrate data
#      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
#    ports:
#      - "7080:7080"
#      - "7443:7443"
#    networks:
#      - local_network
#networks:
#  local_network:
#    driver: bridge
#

services:
  keycloak_novo:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm"]
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - local_network
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring

networks:
  local_network:
    driver: bridge
  monitoring:
    driver: bridge