server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  application:
    name: petshop

  thymeleaf:
    cache: false

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
#      # schema-locations: classpath:schema.sql # descomenta se quiser usar schema.sql

  messages:
    encoding: UTF-8
    basename: messages

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
