server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  security:
    oauth2:
      client:
        provider:
          petshop-realm:
            issuer-uri: http://localhost:7080/realms/petshop-realm
        registration:
          keycloak:
            provider: petshop-realm
            authorization-grant-type: authorization_code
            client-id: api-petshop
            client-secret: 6DbmJOjIUPN6ylheyCnyJ59qLZ3KyD0u
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  application:
    name: petshop



  thymeleaf:
    cache: false

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
#      # schema-locations: classpath:schema.sql # descomenta se quiser usar schema.sql

  messages:
    encoding: UTF-8
    basename: messages

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
