-- Criação da tabela tutor
create table tutor (
                       id bigint generated by default as identity,
                       cpf varchar(11) not null unique, -- Agora o CPF é único
                       email varchar(100) not null,
                       nome varchar(255) not null,
                       telefone varchar(255) not null,
                       primary key (id)
);

-- Criação da tabela animal
create table animal (
                        id bigint generated by default as identity,
                        nome varchar(255) not null,
                        tipo varchar(255) not null,
                        raca varchar(255) not null,
                        data_nascimento date not null,
                        peso float(53) not null check (peso >= 0),
                        sexo tinyint check (sexo between 0 and 1),
                        castrado boolean not null,
                        tutor_cpf varchar(11), -- CPF do tutor
                        primary key (id),
                        foreign key (tutor_cpf) references tutor(cpf) -- Chave estrangeira para o CPF
);

-- Inserts para a tabela tutor
INSERT INTO tutor (cpf, email, nome, telefone) VALUES
                                                   ('12345678901', 'carlos.silva@email.com', 'Carlos Silva', '99 9999-9999'),
                                                   ('98765432100', 'ana.pereira@email.com', 'Ana Pereira', '88 8888-8888'),
                                                   ('11223344556', 'joao.souza@email.com', 'João Souza', '77 7777-7777');

-- Inserts para a tabela animal
INSERT INTO animal (nome, tipo, raca, data_nascimento, peso, sexo, castrado, tutor_cpf) VALUES
                                                                                            ('Rex', 'Cachorro', 'Pastor Alemão', '2020-05-10', 30.5, 0, true, '12345678901'),
                                                                                            ('Luna', 'Gato', 'Siamês', '2019-08-15', 4.2, 1, false, '98765432100'),
                                                                                            ('Max', 'Cachorro', 'Bulldog', '2021-02-20', 10.0, 0, true, '11223344556');
